version: '3'
services:
  jenkins_master:
    build: .
    image: jenkins_ppsea_master
    container_name: jenkins_ppsea_master_container
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
volumes:
  jenkins_home: