apiVersion: v1
kind: BuildConfig
metadata:
  name: jenkins-ppsea-build
spec:
  source:
    type: Git
    git:
      uri: 'ssh://git@git.bmwgroup.net:7999/ppsea/jenkins-template.git'
    sourceSecret:
      name: ppsea-ssh
  strategy:
     type: Source
     sourceStrategy:
      from:
        kind: ImageStreamTag
        name: 'jenkins:latest'
        namespace: openshift
      env:
        - name: OVERRIDE_PV_CONFIG_WITH_IMAGE_CONFIG
          value: 'true'
        - name: INSTALL_PLUGINS
          value: 'maven-plugin:3.0,nodejs:1.2.4,docker-plugin:1.0.4,kubernetes:1.1.3,openshift-sync:0.1.32,openshift-login:1.0.0,openshift-pipeline:1.0.52,config-file-provider:2.16.4'
  output:
    to:
      kind: ImageStreamTag
      name: 'jenkins-ppsea-image:latest'