apiVersion: v1
kind: BuildConfig
metadata:
  name: jenkins-ppsea-build
spec:
  source:
    type: Git
    git:
      uri: 'ssh://git@git.bmwgroup.net:7999/ppsea/jenkins-template.git'
    sourceSecret:
      name: ppsea-ssh
  strategy:
     type: Source
     sourceStrategy:
      from:
        kind: ImageStreamTag
        name: 'jenkins:latest'
        namespace: openshift
      env:
        - name: OVERRIDE_PV_CONFIG_WITH_IMAGE_CONFIG
          value: 'true'
        - name: http_proxy
          value: 'http://PROXY_USER:PROXY_PASS@proxy.muc:8080'
        - name: https_proxy
          value: 'http://PROXY_USER:PROXY_PASS@proxy.muc:8080'
  output:
    to:
      kind: ImageStreamTag
      name: 'jenkins-ppsea-image:latest'