apiVersion: v1
kind: BuildConfig
metadata:
  name: jenkins-ppsea-build
spec:
  source:
    type: Git
    git:
      uri: 'ssh://git@git.bmwgroup.net:7999/ppsea/jenkins-template.git'
    sourceSecret:
      name: ppsea-ssh
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: jenkins:latest
        namespace: openshift
    type: Source
  output:
    to:
      kind: ImageStreamTag
      name: 'jenkins-ppsea-image:latest'